[tools]
aube = "latest"
betterleaks = "latest"
bitwarden-secrets-manager = "latest"
"cargo:lumen" = "latest"
cheat = "latest"
codex = "latest"
glab = "latest"
go = "1.26.5"
node = "latest"
"npm:@kilocode/cli" = "latest"
"npm:freebuff" = "latest"
pi = "latest"
[settings]
experimental = true
