alias aliass "nano ~/.config/fish/conf.d/aliass.fish"
alias genv "nano ~/.config/fish/conf.d/variables.fish"
alias ls "eza  --icons=always"
alias cd "z"
alias npm "bun"
alias npx "bunx"
#alias node "bun"
alias cat "bat"
alias uvsh "source .venv/bin/activate.fish"
alias dig "doggo"
alias vim "nvim"
